### ISSUE TITLE
Ghost-Buttons

### ISSUE THREAD

**Issue by domhaas** [Terence-D/GamingInterfaceClientAndroid#99] opened 2019-11-02 12:32 UTC
Hi there,

I got a strange issue:
It happens that the buttons I've just created are getting duplicated for example when I do a click on them. But not really as a new button, but as a graphic that is on top of my screen:
[Screenshot](https://i.imgur.com/VUYSfg4.jpg)

The weird thing is also that those copies cannot be removed, also when I'm going to exit the GIC-App. I need to do a full reboot to get rid of them. I'm a little bit confused, because how is this possible at all? I mean, isn't there some kind of right management in android for not allowing that? ^^

I'm using a pixel-phone with (official) Android Q.

Thank you in advance.

**Comment by Terence-D** [comment] 2019-11-02 15:24
That is really weird for sure. Let me take a look and see if I can replicate this. There is no way the image should stay after leaving the app.

I have a pixel 2 so should be able to replicate.

**Comment by Terence-D** [comment] 2019-11-05 03:32
I so far have been unable to reproduce.. could you give me the following information:

- Confirm which Pixel  device your using
- Latest version from Play store - beta or release?
- Exact steps to reproduce
- Confirm that if you close GIC by any method - the icons remain overtop of all other applications?  
- Anything else that might be relevant?  Unusual setup, root, etc?  

could you also send me the exact image your using?  support [at ] coffeeshopstudio.ca

Thanks, and sorry about this.

**Comment by domhaas** [comment] 2019-11-05 08:48
> I so far have been unable to reproduce.. could you give me the following information:
> 
>     * Confirm which Pixel  device your using
Pixel 3a - Android Q

>     * Latest version from Play store - beta or release?
4.0.0 (release) from Playstore

>     * Exact steps to reproduce
Trying to reproduce it, currently I'm also not possible to find the issue again. As the issue happened I was playing a longer time with the App and was connected with the Server-Software.
Trying a little bit more and hopefully can create you the steps. 

>     * Confirm that if you close GIC by any method - the icons remain overtop of all other applications?
Yeah, I've closed every GIC (also tried a force quit), also locked screen etc. only reboot was helping.

>     * Anything else that might be relevant?  Unusual setup, root, etc?
Using magisk, should be not causing known issues.

>     * could you also send me the exact image your using? support [at ] coffeeshopstudio.ca
I will send it to you.

>     * Thanks, and sorry about this.
No problem at all, thank you fore creating this app.

**Comment by domhaas** [comment] 2019-11-11 18:22
hey @Terence-D 
I couldn't reproduce it. Closing this ticket for now and going to reopening it, if I got something useful for you.
Anyhow, thanks for the quick reply.

**Comment by Terence-D** [comment] 2019-12-03 03:44
Reopening this as I may have a solution - adding the fix to the 4.1 release.  Issue was background color could be set to transparent (or partially).

**Comment by Terence-D** [comment] 2019-12-10 14:42
Should be resolved in 4.1

**Closed by Terence-D** 2019-12-10 14:42 UTC

**Comment by domhaas** [comment] 2019-12-10 16:00
> Should be resolved in 4.1

Thanks!
